"""initial migration

Revision ID: 66ca251a169a
Revises: 
Create Date: 2026-02-14 20:31:48.342898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66ca251a169a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('__write_test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('__write_test',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('ts', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
